# Define base image - maybe alpine is not a good fit
FROM golang:alpine

# Make a working dir
RUN mkdir /es-client

# Copy the src to the working dir
COPY client-bin /es-client/

# Set the working dir
# WORKDIR /es-client

# Set permission to allow execute
RUN chmod +x /es-client/client-bin

RUN echo $(ls -l /es-client/)

# Run the app
CMD ["/es-client/client-bin", "-endpoint='some.dns.name'", "-port=9000", "-repeat"]