apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimpton-echoweb
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kimpton-echoweb
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: kimpton-echoweb
    spec:
      containers:
      - image: kimpton/go-echoweb
        name: kimpton-echoweb-container
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kimpton-echoweb
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kimpton-echoweb
  type: LoadBalancer
