apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimpton-echoclient
spec:
  replicas: 6
  selector:
    matchLabels:
      app: kimpton-echoclient
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: kimpton-echoclient
    spec:
      containers:
      - image: kimpton/go-echoclient:latest
        name: kimpton-echoclient-container
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
---