apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimpton-echoclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimpton-echoclient
  template:
    metadata:
      labels:
        app: kimpton-echoclient
    spec:
      containers:
      - name: kimpton-echoclient-container
        image: kimpton/go-echoclient:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"