apiVersion: v1
kind: Service
metadata:
  name: kimpton-echoserver-external
  namespace: prod
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: kimpton-echoserver
  type: LoadBalancer
